name: Test for cn-stock-holidays
on:
  push:
    branches:
      - main
      - feature/add-github-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', 'pypy3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .
      - name: Install pytest
        run: pip install pytest
      - name: Run test code
        run: pytest
